# Generated by Django 3.2 on 2021-05-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
