# Generated by Django 3.2 on 2021-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210520_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='introduction',
            field=models.TextField(),
        ),
    ]
