# Generated by Django 3.2 on 2021-05-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_introduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'News'},
        ),
    ]
