# Generated by Django 3.2 on 2021-05-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comment_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
    ]
