# Generated by Django 3.2 on 2021-05-29 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_stripecustomer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
